name: flame_tiled_example
description: Simple project to showcase the usage of flame_tiled
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: ^1.6.0
  flame_ldtk:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^0.2.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ldtk/
    - assets/ldtk/third_map/
    - assets/ldtk/third_map/simplified/
    - assets/ldtk/third_map/simplified/Level_0/
    - assets/ldtk/third_map/simplified/Level_1/
    - assets/ldtk/third_map/simplified/Level_2/
    - assets/ldtk/third_map/simplified/Level_3/
    - assets/ldtk/third_map/simplified/Level_4/
    - assets/ldtk/third_map/simplified/Level_5/
