name: flame_ldtk
description: LDtk support for the Flame game engine. This uses the ldtk package and provides wrappers and components to be used inside Flame.
version: 0.0.1
#homepage: https://github.com/

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.16.0
  flame: ^1.6.0
  flutter:
    sdk: flutter
  meta: ^1.7.0
  ldtk:
    git: https://github.com/foamify/ldtk.dart.git

dev_dependencies:
  dartdoc: ^6.0.1
  flame_lint: ^0.1.3
  flutter_test:
    sdk: flutter
  test: any
