name: flame_ldtk
description: LDtk support for the Flame game engine. This uses the ldtk package and provides wrappers and components to be used inside Flame.
version: 0.1.0
#homepage: https://github.com/

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.17.0
  flame: ^1.6.0
  flutter:
    sdk: flutter
  ldtk:
    git: https://github.com/foamify/ldtk.dart.git
  meta: ^1.7.0

dev_dependencies:
  dartdoc: ^6.1.5
  very_good_analysis: ^4.0.0+1
  flutter_test:
    sdk: flutter
  test: any
